spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/shop
    username: root
    password: 1234
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/init.sql
  kafka:
    bootstrap-servers:
      - 127.0.0.1:9092

logging:
  level:
    root: info

